
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
public class Apotek extends javax.swing.JFrame {

    /**
     * Creates new form Apotek
     */
    public Apotek() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        gejala = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cari = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        ojbodrex = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bodrex = new javax.swing.JLabel();
        counterpain = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panadol = new javax.swing.JLabel();
        promag = new javax.swing.JLabel();
        polysilane = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        cooling5 = new javax.swing.JLabel();
        faktu = new javax.swing.JLabel();
        herocyn = new javax.swing.JLabel();
        tonikum = new javax.swing.JLabel();
        napacin = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(30, 281));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setPreferredSize(new java.awt.Dimension(1200, 494));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(188, 253, 253));
        jPanel8.setPreferredSize(new java.awt.Dimension(300, 494));

        gejala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sakit kepala", "sakit gigi", "nyeri otot", "maag", "sakit tenggorokan", "luka pada dubur", "gatal gatal", "tidak nafsu makan", "sesak napas", "menguatkan badan" }));
        gejala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gejalaActionPerformed(evt);
            }
        });

        jLabel15.setText("================================");

        jLabel16.setText("INFORMASI LEBIH LANJUT");

        jLabel17.setText("================================");

        jLabel18.setText("--- pilih gejala yang anda derita ---");

        cari.setText("temukan obat");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(gejala, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(56, 56, 56))))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel17)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel15))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(cari)))
                        .addComponent(jButton1))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel16)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(29, 29, 29)
                .addComponent(gejala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(cari)
                .addGap(148, 148, 148)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );

        jPanel5.add(jPanel8, java.awt.BorderLayout.LINE_END);

        jPanel2.setBackground(new java.awt.Color(255, 102, 51));
        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));
        java.awt.GridBagLayout jPanel7Layout = new java.awt.GridBagLayout();
        jPanel7Layout.columnWidths = new int[] {0, 25, 0, 25, 0, 25, 0, 25, 0};
        jPanel7Layout.rowHeights = new int[] {0, 25, 0, 25, 0};
        jPanel7.setLayout(jPanel7Layout);

        ojbodrex.setText("BODREX");
        ojbodrex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ojbodrexMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel7.add(ojbodrex, gridBagConstraints);

        jLabel5.setText("COUNTERPAIN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel7.add(jLabel5, gridBagConstraints);

        jLabel6.setText("POLYSILANE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        jPanel7.add(jLabel6, gridBagConstraints);

        jLabel7.setText("PANADOL ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        jPanel7.add(jLabel7, gridBagConstraints);

        jLabel8.setText("PROMAG");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        jPanel7.add(jLabel8, gridBagConstraints);

        bodrex.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\Documents\\NetBeansProjects\\PPVS3\\src\\bodrex.png")); // NOI18N
        bodrex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bodrexMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel7.add(bodrex, gridBagConstraints);

        counterpain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                counterpainMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel7.add(counterpain, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        jPanel7.add(jLabel11, gridBagConstraints);

        panadol.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\panadol-removebg-preview (1).png")); // NOI18N
        panadol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panadolMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        jPanel7.add(panadol, gridBagConstraints);

        promag.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\S04f6fff85c8540ccbbd199360728ac62z-removebg-preview (1).png")); // NOI18N
        promag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                promagMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        jPanel7.add(promag, gridBagConstraints);

        polysilane.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\6f1322212e0c07eafd1b1bd0d6ab9600-removebg-preview (1).png")); // NOI18N
        polysilane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                polysilaneMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        jPanel7.add(polysilane, gridBagConstraints);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\OneDrive\\Documents\\NetBeansProjects\\PPV3\\src\\counterpain.png")); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel7.add(jLabel4, gridBagConstraints);

        jPanel2.add(jPanel7);

        jPanel9.setBackground(new java.awt.Color(204, 255, 255));
        java.awt.GridBagLayout jPanel9Layout = new java.awt.GridBagLayout();
        jPanel9Layout.columnWidths = new int[] {0, 25, 0, 25, 0, 25, 0, 25, 0};
        jPanel9Layout.rowHeights = new int[] {0, 25, 0, 25, 0};
        jPanel9.setLayout(jPanel9Layout);

        cooling5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\10739_15-1-2019_15-0-53-1665781232-removebg-preview (1).png")); // NOI18N
        cooling5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cooling5MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel9.add(cooling5, gridBagConstraints);

        faktu.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\367_28-12-2018_18-3-27-removebg-preview (1).png")); // NOI18N
        faktu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                faktuMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel9.add(faktu, gridBagConstraints);

        herocyn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\herocyn-removebg-preview (1).png")); // NOI18N
        herocyn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                herocynMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        jPanel9.add(herocyn, gridBagConstraints);

        tonikum.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\14a-980x980-removebg-preview (1).png")); // NOI18N
        tonikum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tonikumMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        jPanel9.add(tonikum, gridBagConstraints);

        napacin.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\napacin-removebg-preview (1).png")); // NOI18N
        napacin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                napacinMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        jPanel9.add(napacin, gridBagConstraints);

        jLabel30.setText("COOLING5");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel9.add(jLabel30, gridBagConstraints);

        jLabel31.setText("FAKTU POLICRESULEN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel9.add(jLabel31, gridBagConstraints);

        jLabel32.setText("HEROCYN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        jPanel9.add(jLabel32, gridBagConstraints);

        jLabel33.setText("TONIKUM");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        jPanel9.add(jLabel33, gridBagConstraints);

        jLabel34.setText("NAPACIN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 4;
        jPanel9.add(jLabel34, gridBagConstraints);

        jPanel2.add(jPanel9);

        jPanel5.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1260, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setBackground(new java.awt.Color(0, 51, 102));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\ml logo\\kimiafarma (1).png")); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(682, 160));
        jPanel3.add(jLabel3);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gejalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gejalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gejalaActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
            String selectedOption = (String) gejala.getSelectedItem();
            if (selectedOption.equals("sakit kepala")) {
                JOptionPane.showMessageDialog(null, "Tips: \nPilih obat bodrex", 
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else if (selectedOption.equals("sakit gigi")) {
                JOptionPane.showMessageDialog(null, "Tips: \nPilih obat bodrex", 
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else if (selectedOption.equals("nyeri otot")) {
                JOptionPane.showMessageDialog(null, "Tips: \nPilih counterpain", 
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else if (selectedOption.equals("maag")) {
                JOptionPane.showMessageDialog(null, "Tips: \nPilih polysilane atau promag", 
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else if (selectedOption.equals("sakit tenggorokan")) {
                JOptionPane.showMessageDialog(null, "Tips: \nPilih cooling5", 
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else if (selectedOption.equals("luka pada dubur")) {
                JOptionPane.showMessageDialog(null, "Tips: \nPilih faktu", 
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else if (selectedOption.equals("gatal gatal")) {
                JOptionPane.showMessageDialog(null, "Tips: \nPilih herocyn", 
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else if (selectedOption.equals("tidak nafsu makan")) {
                JOptionPane.showMessageDialog(null, "Tips: \nPilih tonikum", 
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else if (selectedOption.equals("sesak napas")) {
                JOptionPane.showMessageDialog(null, "Tips: \nPilih napacin", 
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } else if (selectedOption.equals("menguatkan badan")) {
                JOptionPane.showMessageDialog(null, "Tips: \nPilih tonikum", 
                        "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }  
    }//GEN-LAST:event_cariActionPerformed

    private void bodrexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bodrexMouseClicked
        // TODO add your handling code here:
        ImageIcon Bodrex = new ImageIcon(getClass().getResource("bodrex.png"));
        JOptionPane.showMessageDialog(null, "Cocok untuk sakit kepala \n"
                + "sakit gigi dan menurunkan demam", 
                "Bodrex", JOptionPane.WIDTH,Bodrex);
    }//GEN-LAST:event_bodrexMouseClicked

    private void counterpainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_counterpainMouseClicked
        // TODO add your handling code here:
        ImageIcon Counterpain = new ImageIcon(getClass().getResource("counterpain.png"));
        JOptionPane.showMessageDialog(null, "meredakan nyeri otot dan nyeri sendi \n"
                + "juga meredakan sakit punggung dan keseleo", 
                "counterpain", JOptionPane.WIDTH,Counterpain);
    }//GEN-LAST:event_counterpainMouseClicked

    private void ojbodrexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ojbodrexMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ojbodrexMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        ImageIcon Counterpain = new ImageIcon(getClass().getResource("counterpain.png"));
        JOptionPane.showMessageDialog(null, "meredakan nyeri otot dan nyeri sendi \n"
                + "juga meredakan sakit punggung dan keseleo", 
                "counterpain", JOptionPane.WIDTH,Counterpain);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void polysilaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_polysilaneMouseClicked
        // TODO add your handling code here:
        ImageIcon polysilane = new ImageIcon(getClass().getResource("polysilane.png"));
        JOptionPane.showMessageDialog(null, "meredakan gejala sakit maag \n"
                + "dan perut kembung akibat asam lambung", 
                "counterpain", JOptionPane.WIDTH,polysilane);
    }//GEN-LAST:event_polysilaneMouseClicked

    private void panadolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panadolMouseClicked
        // TODO add your handling code here:
        ImageIcon panadol = new ImageIcon(getClass().getResource("panadol.png"));
        JOptionPane.showMessageDialog(null, "mengatasi gejala flu dan batuk \n"
                + "juga meredakan demam", 
                "counterpain", JOptionPane.WIDTH,panadol);
    }//GEN-LAST:event_panadolMouseClicked

    private void promagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_promagMouseClicked
        // TODO add your handling code here:
        ImageIcon promag = new ImageIcon(getClass().getResource("promag.png"));
        JOptionPane.showMessageDialog(null, "meredakan sakit maag \n"
                + "juga asam lambung yang naik", 
                "counterpain", JOptionPane.WIDTH,promag);
    }//GEN-LAST:event_promagMouseClicked

    private void cooling5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cooling5MouseClicked
        // TODO add your handling code here:
        ImageIcon cooling5 = new ImageIcon(getClass().getResource("cooling5.png"));
        JOptionPane.showMessageDialog(null, "mengatasi iritasi ringat pada mulut \n"
                + "juga pada tenggorokan", 
                "counterpain", JOptionPane.WIDTH,cooling5);
    }//GEN-LAST:event_cooling5MouseClicked

    private void faktuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_faktuMouseClicked
        // TODO add your handling code here:
        ImageIcon faktu = new ImageIcon(getClass().getResource("faktu.png"));
        JOptionPane.showMessageDialog(null, "mengobati wasir dan gejala peradangan \n"
                + "dan juga luka pada dubur", 
                "counterpain", JOptionPane.WIDTH,faktu);
    }//GEN-LAST:event_faktuMouseClicked

    private void herocynMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_herocynMouseClicked
        // TODO add your handling code here:
        ImageIcon herocyn = new ImageIcon(getClass().getResource("herocyn.png"));
        JOptionPane.showMessageDialog(null, "meredakan alergi, gatal gatal  \n"
                + "dan biang keringan", 
                "counterpain", JOptionPane.WIDTH,herocyn);
    }//GEN-LAST:event_herocynMouseClicked

    private void tonikumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tonikumMouseClicked
        // TODO add your handling code here:
        ImageIcon tonikum = new ImageIcon(getClass().getResource("tonikum.png"));
        JOptionPane.showMessageDialog(null, "menguatkan tubuh \n"
                + "juga menambah nafsu makan", 
                "tonikum", JOptionPane.WIDTH,tonikum);
    }//GEN-LAST:event_tonikumMouseClicked

    private void napacinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_napacinMouseClicked
        // TODO add your handling code here:
        ImageIcon napacin = new ImageIcon(getClass().getResource("napacin.png"));
        JOptionPane.showMessageDialog(null, "meredakan sesak nafas \n"
                + "juga asma", 
                "napacin", JOptionPane.WIDTH,napacin);
    }//GEN-LAST:event_napacinMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Apotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Apotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Apotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Apotek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Apotek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bodrex;
    private javax.swing.JButton cari;
    private javax.swing.JLabel cooling5;
    private javax.swing.JLabel counterpain;
    private javax.swing.JLabel faktu;
    private javax.swing.JComboBox<String> gejala;
    private javax.swing.JLabel herocyn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel napacin;
    private javax.swing.JLabel ojbodrex;
    private javax.swing.JLabel panadol;
    private javax.swing.JLabel polysilane;
    private javax.swing.JLabel promag;
    private javax.swing.JLabel tonikum;
    // End of variables declaration//GEN-END:variables
}
